spring:
  datasource:
    username: local   
server:
  port: 8443
app:
  api:
    version: "v1.1.0"
    title: "USER SERVICE API"
    description: "This serivce is local environment"
    group: "USER SERVICE API"